spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.202.115:3306/forjdbc?characterEncoding=utf8
    username: root
    password: houzhiming
    #\u521D\u59CB\u5316\u6570\u91CF
    dbcp2:
      initial-size: 1
    tomcat:
      #\u6700\u5927\u94FE\u63A5\u7B49\u5F85\u8D85\u65F6\u65F6\u95F4
      max-wait: 60000
      #\u6700\u5927\u6D3B\u8DC3\u6570
      max-active: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
logging:
  level:
    houzm.accumulation.oauth2: debug